Option Strict On
Option Explicit On

Imports System
Imports System.IO
Imports System.Drawing
Imports System.Windows.Forms

Public Class PdfQuoteForm
    Inherits Form

    Private txtProjectName As TextBox
    Private txtNotes As TextBox
    Private lblInfo As Label

    Public Sub New()
        Me.Text = "Export Engineering Report (PDF)"
        Me.Size = New Size(420, 300)
        Me.StartPosition = FormStartPosition.CenterParent
        Me.FormBorderStyle = FormBorderStyle.FixedDialog
        Me.MaximizeBox = False
        Me.BackColor = Color.FromArgb(24, 30, 40)
        Me.ForeColor = Color.White
        Me.Font = New Font("Segoe UI", 9)

        FormHeader.AddPremiumHeader(Me, "Engineering Report", "MetaMech Engineering Tools")

        Dim lblProject As New Label()
        lblProject.Text = "Project Name:"
        lblProject.Location = New Point(20, 60)
        lblProject.AutoSize = True
        Me.Controls.Add(lblProject)

        txtProjectName = New TextBox()
        txtProjectName.Location = New Point(20, 80)
        txtProjectName.Size = New Size(360, 24)
        txtProjectName.BackColor = Color.FromArgb(30, 38, 50)
        txtProjectName.ForeColor = Color.White
        Me.Controls.Add(txtProjectName)

        Dim lblNotes As New Label()
        lblNotes.Text = "Notes:"
        lblNotes.Location = New Point(20, 115)
        lblNotes.AutoSize = True
        Me.Controls.Add(lblNotes)

        txtNotes = New TextBox()
        txtNotes.Location = New Point(20, 135)
        txtNotes.Size = New Size(360, 60)
        txtNotes.Multiline = True
        txtNotes.BackColor = Color.FromArgb(30, 38, 50)
        txtNotes.ForeColor = Color.White
        Me.Controls.Add(txtNotes)

        lblInfo = New Label()
        lblInfo.Text = "Exports a text report of calculations and project data."
        lblInfo.Location = New Point(20, 205)
        lblInfo.Size = New Size(360, 20)
        lblInfo.ForeColor = Color.FromArgb(140, 150, 160)
        Me.Controls.Add(lblInfo)

        Dim btnExport As New Button()
        btnExport.Text = "📄 Export Report"
        btnExport.Size = New Size(140, 35)
        btnExport.Location = New Point(130, 230)
        btnExport.FlatStyle = FlatStyle.Flat
        btnExport.BackColor = Color.FromArgb(0, 120, 215)
        btnExport.ForeColor = Color.White
        btnExport.Font = New Font("Segoe UI", 9, FontStyle.Bold)
        AddHandler btnExport.Click, AddressOf Export_Click
        Me.Controls.Add(btnExport)
    End Sub

    Private Sub Export_Click(sender As Object, e As EventArgs)
        Dim projectName As String = txtProjectName.Text.Trim()
        If projectName.Length = 0 Then projectName = "MetaMech_Report"

        Using sfd As New SaveFileDialog()
            sfd.Title = "Save Engineering Report"
            sfd.Filter = "Text Files (*.txt)|*.txt"
            sfd.FileName = projectName & "_" & DateTime.Now.ToString("yyyyMMdd_HHmmss") & ".txt"
            If sfd.ShowDialog() <> DialogResult.OK Then Return

            Dim content As String = "============================================" & vbCrLf & _
                                    "  MetaMech Engineering Report" & vbCrLf & _
                                    "============================================" & vbCrLf & _
                                    "Project: " & projectName & vbCrLf & _
                                    "Date:    " & DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss") & vbCrLf & _
                                    "============================================" & vbCrLf & vbCrLf

            If txtNotes.Text.Trim().Length > 0 Then
                content &= "Notes:" & vbCrLf & txtNotes.Text.Trim() & vbCrLf & vbCrLf
            End If

            content &= "Generated by MetaMech Design Automation Tool" & vbCrLf

            File.WriteAllText(sfd.FileName, content)

            MessageBox.Show("Report exported:" & vbCrLf & sfd.FileName, _
                            "Export Complete", MessageBoxButtons.OK, MessageBoxIcon.Information)
        End Using
    End Sub

End Class
